services:

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app:delegated # monta código local -> reinicios instantáneos
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

networks:
  my-network:
    driver: bridge
